version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node
        environment:
          RACK_ENV: test
          RAILS_ENV: test
          CIRCLE_TEST_REPORTS: test-reports
      - image: circleci/postgres:latest
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client
      - run: mkdir -p tmp/cache $CIRCLE_TEST_REPORTS
      - run: gem install bundler
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Database
          command: bundle exec rake db:setup --trace
      - run:
         name: Tests
         command: bundle exec rspec
