default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME") %>
  host: <%= ENV.fetch("DB_HOST") %>
  database: <%= ENV.fetch("DB_DEV") %>

test:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME") %>
  host: <%= ENV.fetch("DB_HOST") %>
  database: <%= ENV.fetch("DB_TEST") %>

production:
  <<: *default
  database: scraps_prod
